version: '3.4'

services:
  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    depends_on:
      - sqlservercustomerservice
  sqlservercustomerservice:  
    image: mcr.microsoft.com/mssql/server 
    hostname: 'sqlservercustomerservice'  
    environment:  
      ACCEPT_EULA: 'Y' 
      SA_PASSWORD: "Vignesh@95"  
    volumes:  
      - ./customerapi:/var/opt/mssql/data  
    ports:  
      - '1406:1433'  
    expose:  
      - 1433